version: "3.8"
services:
    backend:
        build: ./server/
        ports:
            - "3003:3003"
        networks:
            - network1
        environment:
            - PORT=3003
            - SECRET=adfaefeq176jyyjhy6hy6
    db:
        build: ./db/
        ports:
            - "3004:3004"
        networks:
            - network1
    frontend:
        build: ./Loginapp/
        ports:
            - "3000:3000"
        networks:
            - network1

networks:
    network1:
        internal: false
